### PR TITLE
Improve BlockInfos: Better info for shelves & bottleracks

### PR DESCRIPTION
**Pull request by DoctorVanGogh**
Two changes:
- **All** bottles in a bottle rack now show detailed info. Before *clay* bottles were explicitly blocked from doing so. That's just mean 👿 
image
- Shelves display info for **all** liquid containers, not just bottles:
image
They also use a somewhat more compact way to display the information.

---

Note that I've changed the harmony patch for the shelf from a Prefix to a Transpiler. Prefixes are the devil. They should be purged from orbit 💥. Gratuitously. :grin:
Transpilers potentially allow others to also muck around in code. Prefixes do not.

---

I _was_ going to also make cooking pots & bowls display the meal contents with this PR, but that's significantly more involved. (*Yuk* compiler generated types & closures are no fun when patching.) Maybe I'll get to that later.

### CODE REVIEW

**Review by l33tmaan — COMMENTED** [review]
I like all of this except the clay bottle change. They're really meant to not display info on the bottle rack - you want that, you upgrade to transparent bottles. Maybe make it a config option?

**Comment by DoctorVanGogh** [comment]
Well, I kinda was afraid you'd put that block there intentionally.

My issue with "hiding" that information is that the very same information is happily displayed when on the shelf... Same bottle. Still as non transparent as in the rack. But on the shelf I can know what's inside. But not in the rack. **That** made no sense to me.

**Comment by l33tmaan** [comment]
> Well, I kinda was afraid you'd put that block there intentionally.
> 
> My issue with "hiding" that information is that the very same information is happily displayed when on the shelf... Same bottle. Still as non transparent as in the rack. But on the shelf I can know what's inside. But not in the rack. **That** made no sense to me.

Good point... that would involve patching the shelf class, wouldn't it? I don't think we do that right now. At that point it might  as well be edited so you can fit 16 bottles onto a shelf, too.

**Comment by DoctorVanGogh** [comment]
Well, EF currently **does** patch the shelf. It's totally doable to hide information there too. 

But where does this end then? Do you want to hide the contents of the bottle while in hand? What has changed there? Has the bottle become transparent when picked up? 😆 I'm head-cannoning small markers on the bottle necks/top in there. Someone with _really_ good art skills might update the clay bottle model to have labels like the crock. I'm not that person. So for now "I magically know what's in there and how old it is" will be good enough for me.

Also: Why do we know what is inside a cauldron when it has been closed? *They* are certainly not made out of glass 😁

**Comment by l33tmaan** [comment]
Oh, you're right! I see it right there. Hah. Good point, you're correct on all this.

**Comment by l33tmaan** [comment]
Uh oh. Looks like there are conflicts that need to be resolved?

**Comment by DoctorVanGogh** [comment]
Well, as I said in #3 :

> Is kinda using (and expands on) some of the helper extensions for https://github.com/l33tmaan/ACulinaryArtillery--l33tFork/pull/2. So maybe hold back on merging this until that one is done and dry. Then I can merge things together nicely.

The idea would have been to merge this one first :D

**Comment by DoctorVanGogh** [comment]
So.,.. merge? no merge? 🍌? 🐔 ?

Doing something else and was wondering where my second transpiler went 😉

**Pull request merged**
